// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMbghnEzWyn5FJThRVWPk5j5xtmq-g35s',
    appId: '1:905667621591:android:9da73fcaab7cc79d7bf692',
    messagingSenderId: '905667621591',
    projectId: 'call-agent-17d65',
    storageBucket: 'call-agent-17d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdAsk6xAqsFFJUACT0jLHcNgqnRof9dmQ',
    appId: '1:905667621591:ios:3951405a256894337bf692',
    messagingSenderId: '905667621591',
    projectId: 'call-agent-17d65',
    storageBucket: 'call-agent-17d65.appspot.com',
    androidClientId: '905667621591-dgbu503rak2ilk2f047pobifjd7d97rk.apps.googleusercontent.com',
    iosClientId: '905667621591-ea6hsa08mg59reuslkgnfk106535qshc.apps.googleusercontent.com',
    iosBundleId: 'com.example.callAgent',
  );
}
